version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:70a5df799b7b141cf93fe2d76c733727bfed389f8142f4044279a4541f65b1b2
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"