version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:31ac80fea910810dea7983e4af19c3835a870b18376d2fd9c2ac371a092c94f7
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"