version: '2'
services:
  ruby:
    image: ruby:3.4-alpine@sha256:238943c2e70e3e502a5e9db8eaa9bd39308414b29affa0253dbd7b6c42a1bb2f
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"