version: '2'
services:
  ruby:
    image: ruby:3.4-alpine@sha256:e97433bb401592615f94bffc5c0dadbf0b161619ebac5a0af044cd7b673a6f12
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"