version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:16541bb777ef7bf4f1865bd9c4c70ffbe22d78d32d08b8104c19684810678c42
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"