version: '2'
services:
  ruby:
    image: ruby:3.4-alpine@sha256:ceef690e705c615e849ca8412016cc773863a58737c69abe1a27f8cce93df0e0
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"