version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:d04c1312316d7f55893c13f6ddb1d98d0e93eba273f50d0df0bd98b26552b5af
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"