version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:d811ee7b48a5cfb646de035f7dac59fd5530c1aef46e9660bd0e65dde307ffa0
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"