version: '2'
services:
  ruby:
    image: ruby:3.4-alpine@sha256:cb6a5cb7303314946b75fa64c96d8116f838b8495ffa161610bd6aaaf9a70121
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"