version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:e0c0edd0db96c7d8ca7590adfc5b08c11f84d3209506c4c4639391981e0f6f36
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"