version: '2'
services:
  ruby:
    image: ruby:3.4-alpine@sha256:e5c30595c6a322bc3fbaacd5e35d698a6b9e6d1079ab0af09ffe52f5816aec3b
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"