version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:650befadad85688e79cbf6ade75cfa049e04cf0d7d51400ee6005bc70017c10f
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"