version: '2'
services:
  ruby:
    image: ruby:3.4-alpine@sha256:487a7b4623ca0b0f635608000ca9bf2d461819fed1cae9b7d5d59b47ef648aac
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"