version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:44a4781564925cf39fc7f1edf19e418f37ebfd8b732816539bba5ff6f284b985
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"