version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:cf8ca08057c41857cadd22b9283090c38b7071ac00894e03d5442a485e522ca6
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"