version: '2'
services:
  ruby:
    image: ruby:3.3-alpine@sha256:caeab43b356463e63f87af54a03de1ae4687b36da708e6d37025c557ade450f8
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"